name: GitHub actions
on:
  pull_request:
    types: [opened, edited]
jobs: 
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn install
      - run: eslint "./**"